version: '3.8'

services:
  frontend:
    build: ./frontend
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
      - ./types/:/usr/src/types

  backend:
    build: ./backend/Dockerfile.dev
    command: npm dev
    ports:
      - 4000:4000
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
      - ./types/:/usr/src/types

  routefinder:
    image: hsldevcom/opentripplanner:prod
    environment:
      - ROUTER_DATA_CONTAINER_URL=http://hsl-data-container:8080
      - ROUTER_NAME=hsl
      - JAVA_OPTS=-Xmx6g
    ports:
      - 9080:8080

  hsl-data-container:
    image: hsldevcom/opentripplanner-data-container-hsl:prod
    ports:
      - 8080:8080
    volumes:
      - ./routefinder/graph-hsl-4edabc8e2571faae4345e7cc686b2215fe1acd0e.zip:/var/www/localhost/htdocs/graph-hsl-4edabc8e2571faae4345e7cc686b2215fe1acd0e.zip

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    ports:
      - 5000:8080
